name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: PreCache
        run: npm version 0.0.0 --no-git-tag-version
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            /home/runner/.cache/Cypress
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  checks:
    name: ESLint - Prettier - TSC
    runs-on: ubuntu-latest
    needs: packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: PreCache
        run: npm version 0.0.0 --no-git-tag-version
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            /home/runner/.cache/Cypress
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run checks

  awx:
    name: AWX
    needs: packages
    uses: ./.github/workflows/component.yml
    with:
      directory: frontend/awx

  eda:
    name: EDA
    needs: packages
    uses: ./.github/workflows/component.yml
    with:
      directory: frontend/eda

  hub:
    name: HUB
    needs: packages
    uses: ./.github/workflows/component.yml
    with:
      directory: frontend/hub

  common:
    name: Common
    needs: packages
    uses: ./.github/workflows/component.yml
    with:
      directory: frontend/common

  framework:
    name: Framework
    needs: packages
    uses: ./.github/workflows/component.yml
    with:
      directory: framework

  success:
    name: Success
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: 
      - checks
      - awx
      - eda
      - hub
      - common
      - framework
    steps:
      - run: echo Success
